FROM alpine:3.21.3

RUN apk upgrade --no-cache
RUN apk add curl

RUN echo '#!/bin/sh' > test.sh && \
    echo 'curl -i -c cookies.txt $COOKIE_APP_URL/get' >> test.sh && \
    echo 'curl -i -b cookies.txt $COOKIE_APP_URL/save' >> test.sh && \
    chmod +x test.sh

CMD ["sh", "test.sh"]
