services:
  cookie-application:
    build:
      dockerfile: Dockerfile-application
    container_name: cookie-application
    image: cookie-application
    environment:
      server.port: 8080
  cookie-client:
    build:
      dockerfile: Dockerfile-client
    container_name: cookie-client
    image: cookie-client
    depends_on:
      - cookie-application
    environment:
      COOKIE_APP_URL: cookie-application:8080